server:
  port: ${SERVER_PORT:7070}

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      ssl:
        enabled: ${REDIS_SSL:false}

shopery:
  base-url: ${SHOPERY_BASE_URL:http://localhost:8080}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    az.shopery: ${LOG_LEVEL:INFO}
    org.springframework.cloud.gateway: ${GW_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"
