server:
  port: ${SERVER_PORT:7070}

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      ssl:
        enabled: ${REDIS_SSL:false}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # public
            - id: shopery-auth
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/auth/**

            - id: shopery-shops
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/shops/**

            - id: shopery-products
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/products/**

            - id: shopery-blogs
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/blogs/**

            - id: shopery-dropdowns
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/dropdowns/**

            - id: shopery-ws
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/ws,/ws/**

            # protected
            - id: shopery-user-me
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/users/me/**

            - id: shopery-admin
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/admins/**

            # fallback for other authenticated endpoints
            - id: shopery-other-api
              uri: ${SHOPERY_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/**

management:
  server:
    port: ${MANAGEMENT_PORT:9090}
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, gateway, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    redis:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_RATE:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

rate-limiter:
  replenish-rate: ${RATE_LIMIT_RPS:20}
  burst-capacity: ${RATE_LIMIT_BURST:40}
  requested-tokens: 1

logging:
  level:
    az.shopery: ${LOG_LEVEL:INFO}
    org.springframework.cloud.gateway: ${GW_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"
